//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drugstore
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DrugstoreEntities : DbContext
    {
        public DrugstoreEntities()
            : base("name=DrugstoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AceeptedGood> AceeptedGoods { get; set; }
        public virtual DbSet<CurrentExchange> CurrentExchanges { get; set; }
        public virtual DbSet<Sold> Solds { get; set; }
        public virtual DbSet<Stash> Stashes { get; set; }
    }
}
